### ISSUE TITLE
Read a whole file into memory 

### ISSUE THREAD

**Issue by baziotis** [ACM-UoA-Student-Chapter/dil#1]
For the compiler, we'll pick a simple and effective scheme to read the input. That is, we will read each file as a whole into memory as a NUL-terminated, contiguous array of characters.

Initially we will have only one input file and we won't support Unicode.

To start off, we can do our job with just a `const char *`. Eventually we might need to make our own `string` class but certainly, it's better to not use `std::string`.

So, we want a function `const char *read_file_into_memory(const char *filepath)`.

**Comment by ssiatras** [comment]
May I work on this one? 

Also, a more general question for the project: Is there preference between high-level C++ commands and low-level system-specific system calls? 

For example on this issue, which one would be better to use?
• istream& get (char* s, streamsize n);
or
• ssize_t read(int fd, void *buf, size_t count);

**Comment by efsiatras** [comment]
May I work on this one? 

Also, a more general question for the project: Is there preference between high-level C++ functions and low-level system-specific system calls? 

For example on this issue, which one would be better to use?
• istream& get (char* s, streamsize n);
or
• ssize_t read(int fd, void *buf, size_t count);

**Comment by baziotis** [comment]
> May I work on this one?

Of course, I'm assigning you. 
> Also, a more general question for the project: Is there preference between high-level C++ functions and low-level system-specific system calls?
> 
> For example on this issue, which one would be better to use?
> • istream& get (char* s, streamsize n);
> or
> • ssize_t read(int fd, void *buf, size_t count);

Whenever there is no significant performance penalty involved or the penalty is not in hot code,
then prefer the high level one because the code is more maintainable.
In this case, even if there was an important penalty with using `istream` (which there isn't),
the code will only run once, in the start. So, unless the penalty is really big, we don't care.
Now, it's important to think of questions like
"What happens with multiple files?", "Is it the best solution to read it all at once?" and maybe
later if the compiler is multi-threaded "how about parallel reading?".
But _all_ these questions are premature optimization and wasted time at this point.

_Note_: Hot code is the parts of a program that have to run fast and usually, multiple times (that's why you will often see the term "hot loop").

**Comment by efsiatras** [comment]
May I use C-style file input/output in order to calculate the size of file properly?

In C++ we have to either read the file char by char or use std::filesystem::file_size of C++ 17.
https://en.cppreference.com/w/cpp/filesystem/file_size

Maybe we need to start a new issue for discussion about the C++ standard version we are going to use eventually.

**Comment by baziotis** [comment]
> May I use C-style file input/output in order to calculate the size of file properly?
> 
> In C++ we have to either read the file char by char or use std::filesystem::file_size of C++ 17.
> https://en.cppreference.com/w/cpp/filesystem/file_size
>

You can do it another way too. But really, do in any way that fits you. Generally,
have in mind that the easiest / less code, the better for this one. That is because it is simple
and so performance is not of much importance (at least for now). So, we want
the easiest code possible.

> Maybe we need to start a new issue for discussion about the C++ standard version we are going to use eventually.

Probably it will be C++14, maybe C++17 but in any case, the C++ that we will use will be pretty
basic. We don't want any C++ craziness.
At some point I will upload a coding guide. Creating one though is actually difficult,
so I don't know exactly when it will be ready, I hope soon.

**Comment by baziotis** [comment]
Everything ok with this?

**Comment by baziotis** [comment]
Solved: https://github.com/ACM-UoA-Student-Chapter/dil/pull/31
