### ISSUE TITLE
Starting the lexer - recognize simple keywords

### ISSUE THREAD

**Issue by baziotis** [ACM-UoA-Student-Chapter/dil#10]
_Note_: I won't try to replace the theoretical background that compiler textbooks and courses 
provide. Certainly github is not the place for that. But I think it's important to give some
description about what we try to do. Feel free to skip it if you already know the basics.

**What is a lexical analyzer (lexer) ?**
One very important thing that a compiler tries to do is _understand_ the input (so that it can
then tell the computer - in assembly language - what to do based on what the input says).

Now, the input, as it goes into the compiler, is essentially a bunch of characters that (initially)
mean nothing. There has to exist some way to separate / group those characters so that
they have some meaning.

Compare that with natural languages: To understand English text, you first have to separate
the input (i.e. a bunch of characters) into words. Because words are the smallest
piece in the English language that _mean_ something. Then of course, we use _combine_
those  words in different ways to create sentences, paragraphs etc. which help us _convey_ information (i.e. meaning, i.e. help the one reading the text _understand_ what we think).

But it all starts with words, the smallest piece of meaning. Kind of like atoms in the physical world.

So, the same way that a natural language has words, a programming language has tokens.
A token is anything that can mean something on its own. The character `+` is a token on its
own, because it means something on its own. The keyword `int` is also a token.

We want to start off with a lexical analyzer that can recognize simple tokens.
Things like `+`, `int`, `return`, `[` etc.

**How do we implement them?**

There are basically 2 ways to implement lexical analyzers:
1) Automatically generated given a lexical specification.
2) Hand-written lexical analyzers.

In 1), there is a program that takes a lexical specification and constructs a program
that acts as a lexer. This may sounded complicated so feel free to ignore it for now.
We won't use that.

For most programming languages, it's easy enough to make the lexical analyzer by hand.
And the usual way is to make an automata-like program. If you don't know what an automata
means, then again don't worry. Basically, we try to decide based on the characters
that we come across, in what token we might be.
That is, if I see `i`, then the token I'm trying to recognize is definitely _not_ e.g. `return`.
It may be `if` or it may be `int`. So, I try to read a second character that will help me decide etc.

In the general case all those are more difficult because there are user-defined tokens, aka
identifiers.
When you write: `int foo;` you have introduced a user-defined identifier - `foo`.
In the same way, `int i;` introduces the identifier `i`, so when you see `i`, it might be `if`, it might
be `int` but it might be `i`.

Feel free to forget those complicated situations for now. Try to focus only on simple
keywords.
There will be a big `switch` that based on the first character that we see, we will try to understand
in what token we're in. Then, we'll test all the rest of the characters for all tokens that start
with the same character. For example:
```C
const char *input = ...;
switch (input[0]) {
case 'i':
{
    if(input[1] == 'f') {
        // We saw `if`
        return;
    }
    if (input[1] == 'n' &&
        input[2] == 't')
    {
        // We saw `int`
        return;
    }
} break;
case 'r':
{
    ...
} break;
}
```

**Comment by nsoul97** [comment]
Can I get an assignment in this one?

**Comment by nsoul97** [comment]
Is it ok if the function returns the token's enumeration as defined in the [tokens.h](https://github.com/ACM-UoA-Student-Chapter/dil/blob/master/tokens.h) file?

Also, what if the input was int123q? Should we return the int enumeration (as described in the example code) or should we also check if the next character after t  is null?

**Comment by jimisdam** [comment]
> Is it ok if the function returns the token's enumeration as defined in the [tokens.h](https://github.com/ACM-UoA-Student-Chapter/dil/blob/master/tokens.h) file?
> 
> Also, what if the input was int123q? Should we return the int enumeration (as described in the example code) or should we also check if the next character after t is null?

Not Null, that's another case. Space Character will do the job, in order to keep the Lexer going on processing the following expressions after each keyword. It's gonna read a File after all and that's why Null is not the case. (That's my perspective of course)

**Comment by nsoul97** [comment]
I get your viewpoint. I was thinking of this course of action you are describing with blank characters in general being the terminating characters of the input string, but idk. Maybe there will be a function parsing the input and separating the .dil file input to strings terminated by null and then we''ll use the identifier function.

**Comment by baziotis** [comment]
Nope, the idea is in the direction that @jimisdam said. When you have found a keyword, e.g. `int`, you should check that the next character is not a character that can appear in an identifier (we need https://github.com/ACM-UoA-Student-Chapter/dil/issues/8 exactly for this kind of checks). Whitespace are such characters but not the only. `/` is one as well, as `+` etc. Because you could write:
```cpp
int int123q, b, c;
c = int123q/b;
```
Of course, hopefully nobody would ever write this code, but the lexer must handle it correctly.

**Comment by baziotis** [comment]
Another thing I should probably have made clear is that when writing the lexer, we should assume that the input is one big NUL-terminated string (i.e. a whole file read in one big string -> issue https://github.com/ACM-UoA-Student-Chapter/dil/issues/1)

**Comment by nsoul97** [comment]
So I wait for issue 8 to be completed?

**Comment by baziotis** [comment]
No, for now you can make a function that tests if a character can be part of an identifier and continue. When issue 8 is ready, we'll use its functionality.

**Comment by nsoul97** [comment]
Is it ok if the function returns both the TOK enumeration of the input string read and also the position of the index for the next token to be read? I believe that the updated index position is needed especially in the case of integer literals (e.g. 12 -> 2 but 0xABC -> 5) and identifiers (e.g. var -> 3 but vars -> 4), since their length is not fixed, as opposed to the length of the keywords (e.g. if -> 2).

**Comment by baziotis** [comment]
For the time being, just make it print what it saw and `return`. When we get to how it will be used, we'll solve these problems.

**Comment by baziotis** [comment]
Implemented in: https://github.com/ACM-UoA-Student-Chapter/dil/pull/30
