### ISSUE TITLE
Avoid working on same things

### ISSUE THREAD

**Issue by Doryanni** [ACM-UoA-Student-Chapter/dil#19]
How exactly can we avoid working on the same issues since we cannot assign ourselves to issues? Shall we leave a comment or something?

**Comment by baziotis** [comment]
Just ask for an assignment e.g. https://github.com/ACM-UoA-Student-Chapter/dil/issues/9#issuecomment-560135762, https://github.com/ACM-UoA-Student-Chapter/dil/issues/1#issuecomment-560020207, https://github.com/ACM-UoA-Student-Chapter/dil/issues/6#issuecomment-559845483.
To be clear, an assignment implies some responsibility and commitment, hence in general
(both in here and in other projects), it's a bad idea to let anyone be able to assign themselves.
Generally if people become constant contributors with good history, the lead developers let them assign themselves or others.

**Edit**: Btw, it's a good question: In general, you can't completely avoid that.

**Comment by baziotis** [comment]
Let me say that in issues that have task lists, for example:
> * [ ]  Expressions
> * [x]  Statements
> * [x]  Functions
> * [x]  Modules)

more than one people can be assigned. Task lists are good for this reason: They separate an issue into parts.

**Comment by baziotis** [comment]
I hope this one was resolved.
