### ISSUE TITLE
Function that scans an integer

### ISSUE THREAD

**Issue by baziotis** [ACM-UoA-Student-Chapter/dil#2]
Write a function that reads integer literals. It should handle base 10, base 8 (octal) and base 16 
(hexadecimal) numbers. It should provide warnings handle erroneous input gracefully.
That includes: out of base digits, overflow.

## Error handling
We want something like `atoi()` but `atoi()` has a bad interface because the function has no way to clearly notify the caller about failure.
A usual idiom in C/C++ is if we have a function that returns a value of a specific type, to pick an invalid value (of this type) that we return to signify that there was an error.
For example say we have a function that is supposed to find a number in an array and return the index of this number. Let's say it returns an `int`. Note that `int` can represent negative values but those are invalid values for an index (array indexes are >= 0).
So, we could pick a specific value out of those invalid values (e.g. `-1`) which we will return to notify the caller that we could not find the number. This is a _contract_ between the caller and callee
and the caller should know about it.

In the same way, functions that are supposed to return a pointer, can use `NULL` to signify failure.

This method of error handling, while good and widely used,
fails when there is _no_ invalid value to pick. In our example, we call a function that reads
an integer value and returns. Well... all possible integer values are valid. What this means is
we have to return 2 values back. One that is the integer value just read and one that holds
if there was an error or not.

Some programming languages provide multiple return value functionality but C / C++ not.
In C / C++ the usual ways to implement this is:
a) By creating a struct that holds those values, for example:
```
typedef read_int_ret {
    int val;
    int error;
} read_int_ret_t;
```
Unfortunately makes the code unnecessarily convoluted by introducing naming all over the place.
So, another way is:
```
int read_int(const char *input, int *val);
```
So, we pass a _pointer_ in which we save the value while what we return signifies the error.

**Comment by nsoul97** [comment]
how should we represent octal number and hexadecimals in the dil language? Should we follow the C way and have 0(zero) and 0x/0X(zero x/X) as prefixes? Can the letters a,b,c,d,e,f in a hex number be both uppper case and lower case?

**Comment by baziotis** [comment]
> how should we represent octal number and hexadecimals in the dil language? Should we follow the C way and have 0(zero) and 0x/0X(zero x/X) as prefixes? Can the letters a,b,c,d,e,f in a hex number be both uppper case and lower case?

Yes, in both the last 2 questions.

**Comment by nsoul97** [comment]
Should there be a third warning if the input string is "","0", "0x" or "0X"? something like empty numerical expression warning

**Comment by baziotis** [comment]
Warnings:
"": Yes
"0": No (this is a valid integer literal, having the value 0).
"0x": Yes
"0X": Yes

**Comment by nsoul97** [comment]
For strings "+" and "-" which warning should we choose?

**Comment by baziotis** [comment]
Note that both of these are not part of the integer literal. This: `+123` is _not_ an integer literal.
It's a unary expression, in which the unary operator `+` is applied to the literal `123`. Same for `-`.
So, you should never get a leading `+` / `-` because it's the job of the lexer to never get one.
Because `+` / `-` is a token itself.
(And this function is not the one that should check that these are handled correctly).

**Comment by baziotis** [comment]
Implemented in https://github.com/ACM-UoA-Student-Chapter/dil/pull/22.
