### ISSUE TITLE
Pick a license

### ISSUE THREAD

**Issue by baziotis** [ACM-UoA-Student-Chapter/dil#20]
This is a discussion thread to choose a software license together. It's an important omission on my part so better add one soon.

For anyone not knowing what a software license is, they can read [this](https://en.wikipedia.org/wiki/Software_license).
In a nutshell: A bunch of rules stating how (and if) one can use or redistribute the software.

I like [choosealicense.com](https://choosealicense.com/) if you want to take a look on the differences between the most popular licenses. I'm thinking about [MIT](https://choosealicense.com/licenses/mit/) which is a very permissive license.

**Comment by Doryanni** [comment]
MIT License  seems like a simple and decent choice.

**Comment by spy-t** [comment]
Yeah I don't think we would want anything less permissive than MIT

**Comment by baziotis** [comment]
Yes, I think it's a bad idea (to have something less permissive). Basically, the other alternative I was thinking is the [Boost License](https://choosealicense.com/licenses/bsl-1.0/). You might want to take a look for educational purposes.

**Comment by baziotis** [comment]
Ok, I was reading some law-specific stuff online about the licenses. I think actually that Boost will serve us better. It seems it's easier to include copyright authors for each specific part of the source without having to make a single copyright claim in the license as in MIT.
There is a workaround for that by saying something like "Copyright to all the authors" and then keeping a specific file with the authors. But I think it's better to have a specific copyright for each file touched so that it's clear which person worked in what.
Finally, Boost does not impose the copyright to be included in the binary.

**Comment by spy-t** [comment]
That's nice I've never heard of that one. Is it in any way affiliated with [boost](https://www.boost.org/)?

**Comment by baziotis** [comment]
> That's nice I've never heard of that one. Is it in any way affiliated with [boost](https://www.boost.org/)?

Yep: https://www.boost.org/users/license.html

**Comment by baziotis** [comment]
Ok guys, please post if there's any objection with Boost until tomorrow because I'd like you, the contributors, to add it asap. It's pretty important!

**Comment by baziotis** [comment]
So, hopefully everyone interested has seen it by now and there's no objection. I'm closing this with the pick being Boost but feel free to comment on this issue if you have a serious objection.
