### ISSUE TITLE
Provide the list of tokens as an enum

### ISSUE THREAD

**Issue by baziotis** [ACM-UoA-Student-Chapter/dil#3]
Provide an `enum class` that will help us identify tokens.

Tokens are the smallest piece of information that the compiler understands.
For example, the characters `in` in C mean nothing. But the characters `int`
mean something - they're one token signifying the keyword `int`.
In the same way a number e.g. `102` is an integer literal token.
We want the list of all possible tokens of DIL.
_Important note_: We want all the possible _categories_ of tokens. That is,
102 and 103 are different tokens but they belong to the same category: integer literals.

You can start off like this:

```
enum class TOK {
    UNDEFINED,  // token of undefined kind (i.e. error)
    EOI,                 // end of input
    INTLIT,             // integer literal
    ...
};
```
The structure we'll use to save tokens we'll have a field of type `TOK` named e.g. `kind`.
Then we can distinguish tokens as: 
```
if (kind == TOK::INT_LIT) {
    // Do something specific for integer literals
}
```

**Comment by nsoul97** [comment]
I'll try this out.

**Comment by baziotis** [comment]
So, assigning?

**Comment by nsoul97** [comment]
So some questions about DIL.
Which of the following will DIL support?
1)switch, case statements
2)const
3)continue, break
4)'++', '--'
5)assignment operators other than '=' (e.g. '+=', '-=', '<<=')
6)ternary operator('?:')
7)bitwise operators (e.g. '<<', '|', '~')

**Comment by baziotis** [comment]
None, at least for now. For the time being, you can assume that all we will use is what is found in the samples.

**Comment by nsoul97** [comment]
Is EOI DIL's EOF or does it represent the ; token at the end of a statement?

**Comment by baziotis** [comment]
The former. `;` is a separate token.

**Comment by nsoul97** [comment]
I found that comments in C are stripped by the preprocessor so they are not considered to be tokens. What about DIL? Will we use a preprocessor before the compilation? In that case `//`, `/*`, `*\` are not tokens, right?

**Comment by baziotis** [comment]
Note that you can write code like `//`, `/*`, `*\` (you can hit edit in my comment to see).
So yes, in C they're usually removed by the preproc although this is not necessary.
DIL won't have a preproc for various reasons, so the comments should be stripped off by the lexer,
the first part of the compiler. Note that `//`, `/*`, `*/` are **_not_** tokens. A token is the least possible piece of information (or entity) that has meaning to a compiler.
By definition, comments have no meaning to the compiler.
The lexer is responsible for providing tokens to the rest of the compiler and so it makes to also strip off comments (rephrased better: ignore them).

**Comment by baziotis** [comment]
Implemented in: https://github.com/ACM-UoA-Student-Chapter/dil/pull/27
