### ISSUE TITLE
Provide a function that returns a text version of a token

### ISSUE THREAD

**Issue by baziotis** [ACM-UoA-Student-Chapter/dil#4]
Interface: `const char *token_name(TOK)`.

Template:
```
const char *token_name(TOK kind) {
    switch(kind) {
    case TOK::EOI:    return "end of input";
    case TOK::INTLIT: return "integer literal";
    ...
    default: assert(0);
    }
    assert(0);
}
```

**Comment by jimisdam** [comment]
Is this supposed to be a typeof thing, like recognizing the type and return it as a string (type's name) ?

**Comment by baziotis** [comment]
No, you pretty much just have to complete the `token_name()` above.

**Comment by baziotis** [comment]
Implemented in: https://github.com/ACM-UoA-Student-Chapter/dil/pull/32
