### ISSUE TITLE
Generic hash table for data identified by a unique pointer

### ISSUE THREAD

**Issue by baziotis** [ACM-UoA-Student-Chapter/dil#5]
Write a generic [linear probing](http://www.cs.rmit.edu.au/online/blackboard/chapter/05/documents/contribute/chapter/05/linear-probing.html) hash table for data that are unique to a string identifier.

**Why linear probing?** 
Linear probing is fast! Period. It is optimized for cache locality as the data are contiguous.
What is more, the operations that are hazardous for a LP HT won't be needed for a compiler.
Those are deletion and non-constant length data. With the last one I mean that when
the hash table is create, we will know exactly how many data it will save.

**Structure**
The data that we will save will be searched by an unique pointer (specifically `a const char *`).
This is a topic of another issue but essentially all the identifiers will be string interned. That is,
equal strings point to the same memory. For example, let's say we save "foo" as a `const char *` in one place and in another. These 2 `const char *` pointers will be equal. What this means
is that essentially the hash table will treat those strings as integers (i.e. the values of pointers).

We will keep 2 parallel arrays. One that will save the actual data and another that saves the
pointers. In that way, we can do the searching in the pointers (very fast) and incur the penalty
only when we find the correct id. At this point we will return the parallel array pointer.

For this hash table we should constrain the data to only be pointers. That's important to save
memory in unused places in the data array because of linear probing (i.e. the hash table won't be full of course).

**Comment by spy-t** [comment]
Sorry if this has been made clear before but because I'm intending to start with this issue, will the implementation language be C or C++?

**Comment by baziotis** [comment]
C++, I haven't explicitly mentioned it anywhere. Best of luck with this issue, post any questions you might have.

**_Note on interface decisions_** (you might want to skip it):
Clarification: When I'm referring to "interface", I mean the way any abstracted piece of code interacts with the outer world. For example, a function is an abstraction: It does something but you don't necessarily know / care _how_. The interface of the function (and what you should definitely care about) is: what it does, what it gets as input, what it returns as output. In the same way, for a class are its methods and properties.

The best way to decide the correct interface is _by writing the usage code first_ (as Casey Muratori says). That is, if you want to make a function that does the X, then instead of starting from _writing_ the function, start from _using_ the function. For example, if at some point in my code I need a function that gets an `X` and returns a `Y`, I will write:
```
X x = ...;
Y y = my_function(x);
```
without knowing how `my_function()` will be implemented.
The reason that this is good is because any abstraction should be written depending on how it will be used, because any abstraction's purpose is to make your life easier by using it. Hence, start
by how you would like to _use_ it, then come back and start thinking about how to implement it
to conform with this usage. By using it first, you will simply find all the nitty gritty details about its implementation that you otherwise should have to _guess_ (if you started from first implementing it).
And you know how effective guessing is...

Why do I mention that here? Because in this issue, I asked you to implement a data structure (an abstraction), without you having the code that uses it. It just _happens_ that in this case, I've already
used and implemented this abstraction before, so I know the details. In general, I don't and you don't.
So, in general, IMO this is not good practice. But hey, it is a good issue. :)

**Comment by DangWang** [comment]
Has this issue been assigned to somebody already?

**Comment by baziotis** [comment]
Implemented in https://github.com/ACM-UoA-Student-Chapter/dil/pull/17.
