### ISSUE TITLE
String interning

### ISSUE THREAD

**Issue by baziotis** [ACM-UoA-Student-Chapter/dil#6]
Interning strings means that we keep only one copy in memory of each unique string.
For example, let's say we want to save the string "foo". Then, we allocate some memory to save its chars. If we then want again to save "foo", instead of allocating new memory,
we point again to the same previous memory.
That means a couple of things:
- We don't waste memory.
- Remember that a string is essentially a pointer to char. If we keep only one copy around, then
pointers of the same string point to same memory. That means that a string is now identified
by an integer value (the value of the pointer). This makes the rest of the compiler _very_ fast
as it works with integers instead of whole strings.

For now it's better to start with the easiest way that you can think of implementing this.
Then, we'll improve it.

**Comment by J1635** [comment]
I'd like to work on this one, can I get assignment?

**Comment by J1635** [comment]
Are there any restrictions regarding what we can use to develop our programs. For example in cpp, can we use vector and String?

**Comment by baziotis** [comment]
In general no, we just want sane C++. Now because this is an educational project and because vector and string will create more problems than they'll solve, please refrain from using them. I think that without them it will be easier.

**EDIT**: Sorry, I just realized that for an easy solution, the vector will make your life easier. You may use it.

**Comment by baziotis** [comment]
Implemented in: https://github.com/ACM-UoA-Student-Chapter/dil/pull/18.
