### ISSUE TITLE
DIL Grammar

### ISSUE THREAD

**Issue by baziotis** [ACM-UoA-Student-Chapter/dil#7]
Grammar construction is one thing that I assume most people are not experienced with making.
However, I think it's worth it for you to try it. You can check the samples to try to understand the grammar, then try to construct the [EBNF](https://en.wikipedia.org/wiki/Extended_Backus%E2%80%93Naur_form).

To separate the effort, here's a list that I can hope I can make more detailed:
- [x] Expressions
- [x] Statements
- [x] Functions
- [x] Modules

DIL will follow an LLVM-like structure (as many other languages). That is, the top-level entity
is a module, which you can think as a file. A module has 0 or more functions.
A function has 0 or more statements. And a statement can use / contain expressions.

_Note:_ Αn important difference with e.g. C / C++ is that expressions are not intermingled with
statements and vice versa. In C, the assignment is both a statement and an expression, e.g.
you can do this: `a = b = c`; where `b = c` acts both as a statement and an expression.

If you're interested in this issue but you have no experience in formal grammars, we can incrementally build the grammar on Slack, starting from very easy grammars.

**Comment by Doryanni** [comment]
Since this is a project supposed to be accessible by most students with some code development under their belts, should the grammar be LL(1) or should we aim for something different?

**Comment by baziotis** [comment]
Right, LL(1). Generally, even in programming languages for which the compilers are developed from pretty experienced people, we aim for LL(1) grammars. That is because they're easier to lex / parse. Easier code means more maintainable and bug-free code. That said, LL(2) is also acceptable.

**Comment by Doryanni** [comment]
Oh,  since I've already begun, may I be assigned to this issue?

**Comment by baziotis** [comment]
Of course!

**Comment by baziotis** [comment]
We completed a first draft with this: https://github.com/ACM-UoA-Student-Chapter/dil/pull/21
Closing for now.
