### ISSUE TITLE
Character map

### ISSUE THREAD

**Issue by baziotis** [ACM-UoA-Student-Chapter/dil#8]
Create a character map that will help us check if a character belongs to a certain category.
For example, it will help us check if a character is an octal digit. Or if a character can appear in the middle of an identifier.

More specifically, we need to be able to check if the character:
- is blank (space, tab etc.)
- can appear in the middle of an identifier.
- is an octal digit.
- is a hexadecimal digit.
- can appear at all in the a DIL program.

That last one may be unfamiliar to most. Try to include the character `@` in any place in a
C program and compile. The character `@`, maybe interestingly, can't appear in a C program (that
doesn't mean it can't appear in a DIL program).

This issue deliberately has a vague description. I think it's interesting to discuss what the best
way to achieve the goal is.

**Comment by TheodoreAlenas** [comment]
{'+', '-', '*', X, 'a', 'z', '0', '9', '\0'}

could mean "I contain +-* and from a to z and from 0 to 9".
This is practical because hexadecimal digits would be
{X, '0', '9', 'a', 'f', 'A', 'F', '\0'}
all in all.

X here is a character value noone will ever use, such as 0x0 or 0x1.

So we could make such arrays in a header file, as well as a function that helps identify if a character is "included" in such an array.

By the way, I don't know much about maps but STL maps in C++ don't seem relative to this problem.

**Comment by baziotis** [comment]
TBH, I didn't really understand what you're describing. You just want a way to query a data structure with a character and see if it is of a specific kind. Conceptually something like:
```cpp
char c = ...;
if (map.is_octal(c)) { ... // blah }
```
Let me re-iterate that this is the _conceptual_ idea. What you have to do is much simpler.

**Comment by nsoul97** [comment]
@TheodoreAlenas have you started this issue?

**Comment by TheodoreAlenas** [comment]
No no, of course not. I barely understood it. 😄

**Comment by baziotis** [comment]
> No no, of course not. I barely understood it.

If there's something you don't completely understand at first but you are willing to understand it, please request more info. It's totally acceptable for you to not understand something and for me to not have explained something the best way possible.

You might want to start with another question. Let's say I'm requesting a program from you that should behave as follows. I give you the list of all the ASCII characters (which are 256). For each one, I have a number next to it, like (note that I use the decimal value of each character and not how it's printed, 0 here means the character with decimal value zero (which is the NUL character) and not the _digit_ 0 (which has decimal value 48, as you can see in the [ascii table](https://www.asciitable.com/)):
```
0 -> 3
1 -> 7
2 -> 4
... etc.
```
The numbers for each character have no specific pattern, but you have the whole list.
Then I tell you "I should give the program a character and it should print the number that is next to it in the list I gave you". How would you implement this?

**Comment by TheodoreAlenas** [comment]
@baziotis so we are talking about either a function or, like you implied with "map.isoctal('c')", a static constant object of a single-use class.

I get it then. Though I don't see why we need to propose ideas on how to do it, it seems very straightforward.

**Comment by TheodoreAlenas** [comment]
@nsoul97 do you want to try the issue? Because you said it first.

**Comment by baziotis** [comment]
> @baziotis so we are talking about either a function or, like you implied with "map.isoctal('c')", a static constant object of a single-use class.
> 
> I get it then. Though I don't see why we need to propose ideas on how to do it, it seems very straightforward.

Because it is difficult to think simple! For example, I'm thinking of a different solution than the 2 you proposed. And let me clarify yet again that `map.is_octal(c)` is the **_conceptual_** idea. It was not meant to imply that we will use a class.

**Comment by nsoul97** [comment]
@TheodoreAlenas  go ahead I' ll get started with another issue.

**Comment by TheodoreAlenas** [comment]
@nsoul97 Thanks! Good luck!

**Comment by TheodoreAlenas** [comment]
> @baziotis so we are talking about either a function or, like you implied with "map.isoctal('c')", a static constant object of a single-use class.
> I get it then. Though I don't see why we need to propose ideas on how to do it, it seems very straightforward.
> 
> Because it is difficult to think simple! For example, I'm thinking of a different solution than the 2 you proposed. And let me clarify yet again that map.is_octal(c) is the conceptual idea. It was not meant to imply that we will use a class.

Sorry for the late response, I didn't notice your reply. Seriously though, what else is there? A namespace of functions, maybe, or containers that contain the characters  of a category. So what were you thinking instead?

**Comment by baziotis** [comment]
I think that if you answered the alternative question I proposed above, it will be more obvious. :)

**Comment by TheodoreAlenas** [comment]
@baziotis That is interesting, I would implement the alternative problem with an STL map 😲! But... What does that have to do? Are we going to map all the ASCII characters one by one to some enum? Isn't this poor rogramming practice?

**Comment by baziotis** [comment]
> @baziotis That is interesting, I would implement the alternative problem with an STL map !

Alright, do you think this is the simplest solution?

> But... What does that have to do? Are we going to map all the ASCII characters one by one to some enum? Isn't this poor rogramming practice?

Have faith that I don't (try to) waste your time ;)

**Comment by TheodoreAlenas** [comment]
@baziotis something simpler would be a function that has a list in the background... Or even not a function, just a plain list. Maybe the first element of the list corresponds to the first "meaningful" ASCII character and the last element to the last, to half the work and memory. Is that getting somewhere?

**Comment by baziotis** [comment]
Well... That's worse than the STL map :/
How about this:
```cpp
int map[256];
map[0] = 3;
map[1] = 7;
map[2] = 4;
...
```
This is the example I had given above. Note how easily you can implement what was asked. It's simply a matter of getting the value of the array at the character I give you every time, like:
```cpp
while ((c = getchar()) != EOF)
  printf("%d\n", map[c]);
```
Does that make any sense?

**Comment by TheodoreAlenas** [comment]
@baziotis Yes, in fact it is so simple that it twists my mind. Are you sure? Are we not prone to mistakes if we make the character map in a similar way? You know, missing a list element or mixing up the character codes.

**Comment by baziotis** [comment]
> @baziotis Yes, in fact it is so simple that it twists my mind. Are you sure? Are we not prone to mistakes if we make the character map in a similar way? You know, missing a list element or mixing up the character codes.

In this problem, it's easy to verify that you did not miss anything. Note that you're supposed to map _all_ 256 chars. So you can initialize all the elements to a value not existent in the list, do what you have to do, then run a loop to verify that no element is of the initial value.
What do you mean about mixing up codes?

**Comment by TheodoreAlenas** [comment]
May I work on this one? Would you assign me?

**Comment by baziotis** [comment]
Yes!

**Comment by baziotis** [comment]
Implemented in: https://github.com/ACM-UoA-Student-Chapter/dil/pull/28
