### ISSUE TITLE
Colored error messages

### ISSUE THREAD

**Issue by baziotis** [ACM-UoA-Student-Chapter/dil#9]
Write a variadic template function that displays syntax error messages. You might not know what template or variadic means but trust me, if you do want to learn, this is a very easy issue.
We basically want a function that we can e.g. write: `syntax_error("Invalid character literal");`
And get `Syntax Error: Invalid character literal`. But, we want the `Syntax Error:` part to
be **colored**. Preferably red. :)

Still though I haven't explained why do we need the function to be a variadic template function.
Well, we need to do things like this:
```
const char *id = ...;
...
syntax_error("Type with id: ", id, " is invalid.");
```
So, note that we pass multiple typed parameters in the function. And we want to pass
as many as we want. Those 2 together most of the time mean variadic templates.
The function should be able to recognize that `id` is of type `const char *` and print it
accordingly.

But that is maybe not the easiest thing in the world. You may want firstly to start with a function
that just prints one string. Then, multiple strings (with variadic templates), then try to recognize
different types etc.

**Comment by billsioros** [comment]
I would like to address this issue. Is there anything else that I should bare in mind while implementing this feature, like avoiding the usage of iostream e.t.c ?

**Comment by baziotis** [comment]
> I would like to address this issue.

Ok, you got an assignment.
> Is there anything else that I should bare in mind while implementing this feature, like avoiding the usage of iostream e.t.c ?

Yeah, better just use `printf`. Unless there is something quite useful that `iostream` provides that
`printf` doesn't and I haven't thought about it. Now that I think of it, with `iostream` one would probably do it very differently than what I have in mind (this different way is not good IMO). Let's not spoil it, feel free to propose ideas with or without `iostream` (or whatever you want).

**Comment by billsioros** [comment]
I have come up with a solution that uses recursive calls and I would like to get rid of them and make everything a single statement.

One solution to this issue would be using the C Preprocessor, while another one would be implementing a constexpr string.

Is any one of the two more preferable?

Edit: The C Preprocessor is considered by many a bad practise but I consider it simply a tool, while constexpr string results in memory consumption and makes the implementation a tiny bit more complicated.

**Comment by baziotis** [comment]
> I have come up with a solution that uses recursive calls and I would like to get rid of them and make everything a single statement.
> 
> One solution to this issue would be using the C Preprocessor, while another one would be implementing a constexpr string.
> 
> Is any one of the two more preferable?
> 
> Edit: The C Preprocessor is considered by many a bad practise but I consider it simply a tool, while constexpr string results in memory consumption and makes the implementation a tiny bit more complicated.

No need to be extra fancy here. :) Your other solutions are great but let's start with the first solution and we'll see. As part of this project, I'd like to stress that in real software, start simple first.
No need to go for the top shelf. Or as Jonathan Blow says: "Start with the 'it's good for now...' solution. Because the good for now might end up be good enough for shipping".
Plus, if I'm thinking the same thing with you, the overhead with the recursive calls is not
in the runtime but on the compile-time.

**Comment by baziotis** [comment]
My bad, didn't mean to close the issue.

**Comment by billsioros** [comment]
> Plus, if I'm thinking the same thing with you, the overhead with the recursive calls is not
> in the runtime but on the compile-time.

I' m recursively calling printf with different formatting options based on the type at hand and that' s what I want to avoid.

I would like to construct the full formatting string at compile time and then supply the parameter pack directly to printf.

My current implementation works but could definitely be better from a performance standpoint.

**Comment by baziotis** [comment]
> I' m recursively calling printf with different formatting options based on the type at hand and that' s what I want to avoid.
>

Why?

> I would like to construct the full formatting string at compile time and then supply the parameter pack directly to printf.
> 
> My current implementation works but could definitely be better from a performance standpoint.

Is that true? Could it be faster? :)

**Comment by billsioros** [comment]
print("Hello", 12, 0.2f) results in 3 printf statements printf("%s", "Hello"), printf("%d", 12), printf("%f", 0.2f)

> Why?

Well I have to specify the formatting flag coresponding to the type of the variable at hand.

> Is that true? Could it be faster? :)

By creating the full formatting string, which in the previous example would be "%s "%d %f", only a single printf call would suffice.

**Comment by baziotis** [comment]
I agree with all that, it's good thinking. But my point is: We're wasting time if we start thinking about all that unless _we know for a fact_ that one solution is way better than the other.

**Comment by baziotis** [comment]
I agree with all that, it's good thinking. But my point is: We're wasting time if we start thinking about all that unless _we know for a fact_ that one solution is way better than the other. Or another way
to think of it is: We know that the simple solution is really bad. In any other case, we should not care. Definitely, not right now.

And to be a little more specific, performance tuning is not only about finding the best algorithm or even writing the best code. If you were to optimize this, the first question you should ask is: How may times is this function called ?

What I mean is that performance tuning includes 2 very important things that we can't fully know right now:
- Profiling
- Probabilities / Statistics
and that's only about **runtime** performance.

The second question that should be asked is: How many times is this function compiled?
That considers **compile-time** perf.
Using `constexpr` means that you will invoke some kind of interpreter in compile-time (that's what Clang does, previously it had a tree evaluator which was even slower).
If the function is called maximum 30 times but it is compiled 3000 times, then we will incur an important compile-time penalty which is not worth it.

In cases where we don't have any of those, shouldn't we write the simplest, easiest, more debuggable, maintaible and flexible (i.e. can be easily changed if we decide to optimize it) code?

**Comment by billsioros** [comment]
I have made a pull request (#23) concerning this issue. I hope it is good enough to start with. I tried to keep extensibility in mind but I might have cut a few corners.

**Comment by baziotis** [comment]
I'll take a look asap. _Note_: When opening a PR for an issue, don't write it in the comments of the issue. Rather, reference the issue in the PR description, e.g. "Solving issue: URL_OF_THE_ISSUE". That way, Github automatically makes a reference on the issue (e.g. here). Similarly, write any info about the PR _in the PR_. :)

**Comment by billsioros** [comment]
Ok I' ll bear that in mind. I have written the desired info in the PR but haven' t mentioned it. Gonna do that right now !

**Comment by baziotis** [comment]
Implemented in: https://github.com/ACM-UoA-Student-Chapter/dil/pull/23
